### ISSUE TITLE
sueezelite

### ISSUE THREAD

**Issue by antonellocaroli** [lmiphay/gentoo.overlay#5]
Thank you for updating ...
but it seems that it does not work well ... loses some options

`Squeezelite v1.9.0-1105, Copyright 2012-2015 Adrian Smith, 2015-2018 Ralph Irving. See -t for license terms
Usage: squeezelite [options]
  -s <server>[:<port>]	Connect to specified server, otherwise uses autodiscovery to find server
  -o <output device>	Specify output device, default "default", - = output to stdout
  -l 			List output devices
  -a <b>:<p>:<f>:<m>	Specify ALSA params to open output device, b = buffer time in ms or size in bytes, p = period count or size in bytes, f sample format (16|24|24_3|32), m = use mmap (0|1)
  -a <f>		Specify sample format (16|24|32) of output file when using -o - to output samples to stdout (interleaved little endian only)
  -b <stream>:<output>	Specify internal Stream and Output buffer sizes in Kbytes
  -c <codec1>,<codec2>	Restrict codecs to those specified, otherwise load all available codecs; known codecs: flac,pcm,mp3,ogg,aac (mad,mpg for specific mp3 codec)
  			Codecs reported to LMS in order listed, allowing codec priority refinement.
  -C <timeout>		Close output device when idle after timeout seconds, default is to keep it open while player is 'on'
  -d <log>=<level>	Set logging level, logs: all|slimproto|stream|decode|output, level: info|debug|sdebug
  -e <codec1>,<codec2>	Explicitly exclude native support of one or more codecs; known codecs: flac,pcm,mp3,ogg,aac (mad,mpg for specific mp3 codec)
  -f <logfile>		Write debug to logfile
  -m <mac addr>		Set mac address, format: ab:cd:ef:12:34:56
  -M <modelname>	Set the squeezelite player model name sent to the server (default: SqueezeLite)
  -n <name>		Set the player name
  -N <filename>		Store player name in filename to allow server defined name changes to be shared between servers (not supported with -n)
  -W			Read wave and aiff format from header, ignore server parameters
  -p <priority>		Set real time priority of output thread (1-99)
  -P <filename>		Store the process id (PID) in filename
  -r <rates>[:<delay>]	Sample rates supported, allows output to be off when squeezelite is started; rates = <maxrate>|<minrate>-<maxrate>|<rate1>,<rate2>,<rate3>; delay = optional delay switching rates in ms
  -O <mixer device>	Specify mixer device, defaults to 'output device'
  -L 			List volume controls for output device
  -U <control>		Unmute ALSA control and set to full volume (not supported with -V)
  -V <control>		Use ALSA control for volume adjustment, otherwise use software volume adjustment
  -X 			Use linear volume adjustments instead of in terms of dB (only for hardware volume control)
  -z 			Daemonize
  -t 			License terms
  -? 			Display this help text
`
type quell for the DSD "-D"

`Squeezelite v1.8.7-1007, Copyright 2012-2015 Adrian Smith, 2015-2017 Ralph Irving. See -t for license terms
Usage: squeezelite [options]
  -s <server>[:<port>]	Connect to specified server, otherwise uses autodiscovery to find server
  -o <output device>	Specify output device, default "default", - = output to stdout
  -l 			List output devices
  -a <b>:<p>:<f>:<m>	Specify ALSA params to open output device, b = buffer time in ms or size in bytes, p = period count or size in bytes, f sample format (16|24|24_3|32), m = use mmap (0|1)
  -a <f>		Specify sample format (16|24|32) of output file when using -o - to output samples to stdout (interleaved little endian only)
  -b <stream>:<output>	Specify internal Stream and Output buffer sizes in Kbytes
  -c <codec1>,<codec2>	Restrict codecs to those specified, otherwise load all available codecs; known codecs: flac,pcm,mp3,ogg,aac,dsd (mad,mpg for specific mp3 codec)
  			Codecs reported to LMS in order listed, allowing codec priority refinement.
  -C <timeout>		Close output device when idle after timeout seconds, default is to keep it open while player is 'on'
  -d <log>=<level>	Set logging level, logs: all|slimproto|stream|decode|output, level: info|debug|sdebug
  -e <codec1>,<codec2>	Explicitly exclude native support of one or more codecs; known codecs: flac,pcm,mp3,ogg,aac,dsd (mad,mpg for specific mp3 codec)
  -f <logfile>		Write debug to logfile
  -m <mac addr>		Set mac address, format: ab:cd:ef:12:34:56
  -M <modelname>	Set the squeezelite player model name sent to the server (default: SqueezeLite)
  -n <name>		Set the player name
  -N <filename>		Store player name in filename to allow server defined name changes to be shared between servers (not supported with -n)
  -W			Read wave and aiff format from header, ignore server parameters
  -p <priority>		Set real time priority of output thread (1-99)
  -P <filename>		Store the process id (PID) in filename
  -r <rates>[:<delay>]	Sample rates supported, allows output to be off when squeezelite is started; rates = <maxrate>|<minrate>-<maxrate>|<rate1>,<rate2>,<rate3>; delay = optional delay switching rates in ms
  -D [delay]		Output device supports DSD over PCM (DoP), delay = optional delay switching between PCM and DoP in ms
  -O <mixer device>	Specify mixer device, defaults to 'output device'
  -L 			List volume controls for output device
  -U <control>		Unmute ALSA control and set to full volume (not supported with -V)
  -V <control>		Use ALSA control for volume adjustment, otherwise use software volume adjustment
  -X 			Use linear volume adjustments instead of in terms of dB (only for hardware volume control)
  -z 			Daemonize
  -t 			License terms
  -? 			Display this help text

Build options: LINUX ALSA EVENTFD DSD
`

**Comment by lmiphay** [comment]
Try now? 

The Makefile should be selecting the correct options with db80b7e

**Comment by antonellocaroli** [comment]
now it's OK
