### ISSUE TITLE
media-sound/squeezelite

### ISSUE THREAD

**Issue by antonellocaroli** [lmiphay/gentoo.overlay#7]
hi,
I was trying to pull out an ebuild for version 1.9.4.

but I failed, it always gives me an error with the patches.

Do you have any ideas?

**Comment by lmiphay** [comment]
Hi @antonellocaroli 

Can you try the version I just pushed, and let me know if it works for you?

Open an issue if it doesn't, so we can track it.

Thanks,

Paul

**Comment by antonellocaroli** [comment]
perfect. it works.
thanks,
filippo
