### ISSUE TITLE
kde.misc/semantik post install failed

### ISSUE THREAD

**Issue by TheSiege** [lmiphay/gentoo.overlay#8]
Hi,

I've been trying your semantik ebuild but I get the following error:

```
Files matching a file type that is not allowed:
   usr/lib/libsemantik.so.1.2.3
 * ERROR: kde-misc/semantik-9999::localrepo failed:
 *   multilib-strict check failed!
```
[build.log](https://github.com/lmiphay/gentoo.overlay/files/3614026/build.log)

emerging with `FEATURES=-multilib-strict emerge semantik` works though

**Comment by lmiphay** [comment]
Hi @TheSiege 

Give the latest version of -9999 a try and let me know if it still breaks? I think it should be ok.

Thanks,

PAul

**Comment by TheSiege** [comment]
Yes that fixes it! Thanks!
